title: MP MLG Wiki
description: Личная вики по лору
theme: null
markdown: kramdown

# ВАЖНО: Включаем обработку папки _characters
collections:
  characters:
    output: true       # Разрешить генерацию HTML файлов
    permalink: /:title/ # Ссылки будут вида site.com/mp/

# Настройки по умолчанию для этой коллекции
defaults:
  - scope:
      path: ""
      type: "_characters"
    values:
      layout: "character"
      permalink: /:title/