title: MP MLG Wiki
description: Личная вики
theme: null
markdown: kramdown

# ВАЖНО: Укажите имя репозитория здесь
baseurl: "/MP_MLG_WIKI"
url: "https://xelleet.github.io"

collections:
  characters:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"